### PR TITLE
Do not overwrite AWS config when sync fails

### PR DESCRIPTION
**Pull request by sosheskaz**
Fix issue #386 by writing the generated AWS config to a temp file, and replacing current AWS config if and only if all registry syncs succeed.

### What changed?

When `granted registry sync` fails, do not alter ~/.aws/config.

### Why?

Overwriting ~/.aws/config on failure creates a dangerous situation. If Github (or whatever VCS is being used) is down, and the sync runs automatically, then users are be unable to use the service.

Also, on machines that may not be connected to the VCS 24/7 (e.g. VPN, scheduled network outage, not connected to internet), granted registry sync may run automatically, leading to an inconvenience for a user because `granted registry sync` must be re-run manually.

### How did you test it?

1. `granted registry sync`
2. `wc < ~/.aws/config`
  1. `95488`
3. Disconnect network
4. `granted registry sync`
5. `wc < ~/.aws/config`
  1. With current version: `0`
  2. With this version (i.e. using `dgranted` instead of `granted`): `95488`

### Potential risks

This changes behavior which was previously intentional. However, I think that the downside of this is too high. Currently, we are effectively suppressing failures, and breaking the environment in the process. This will make the error louder, and more explicit.

There may be an argument that both failure modes should be supported. However, as a "Principle of Least Surprise" thing, I feel very strongly that this should be the default behavior. 

### Link to relevant docs PRs

### CODE REVIEW

**Comment by Eddie023** [comment]
Thanks for the PR @sosheskaz. I do agree with your proposed change. However, this change can be a configurable option for backward compatibility and for people who would like the previous flow.

**Comment by sosheskaz** [comment]
done

**Review by Eddie023 — APPROVED** [review]

**Comment by chrnorm** [comment]
Thankyou @sosheskaz and thankyou @Eddie023 for the review 🙌 🙌

**Comment by gautamg795** [comment]
FYI, per #600 it looks like this broke setups where `/tmp` is on a different device than `/home` (or wherever the user's AWS config might be stored)

It might be safer to open a temporary directory under the same path as the existing config file?

**Pull request merged**
