### PR TITLE
Delete former credentials when rotating (`granted credentials rotate`)

### PR DESCRIPTION
**Pull request by n3s7or**
### What changed?
Added code to delete old credentials.

### How did you test it?
I rotated my own AWS credentials

### Is patch release candidate?
No

### Link to relevant docs PRs

### CODE REVIEW

**Review by chrnorm — APPROVED** [review]
Thankyou @n3s7or!!

**Review by chrnorm — CHANGES_REQUESTED** [review]
Actually, just looking through the PR and original issue #388 and it would be good to introduce this as opt-in behaviour. Could you please add a flag `--delete` to the command, and then only delete the key if the flag is set?

You can do so by adding
```go
&cli.BoolFlag{Name: "delete", Usage: "delete the previous active key"}
```
to the command definition and then using

```go
if c.Bool("delete") { }
```

to check if the flag is set.

**Comment by n3s7or** [comment]
Thanks for your input @chrnorm
The change is done :)

**Review by chrnorm — APPROVED** [review]
🙌 thankyou @n3s7or!

**Pull request merged**
